apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ms-image-processor
spec:
  type: service
  lifecycle: production
  owner: divicon-team
  system: divicon
  dependsOn:
    - component:keycloak
    - component:lb-app-settings
    - component:lb-keycloak-auth-lib
    - component:lb-queue-services
    - component:graphql-utilities-microservices