app:
  title: ${APP_TITLE}
  baseUrl: ${APP_BASE_URL}

organization:
  name: ${ORG_NAME}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen: ${BACKEND_LISTEN}
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy: {}

techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local

auth:
  providers:
    guest: {}

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration

  rules:
    - allow: [Component, System, API, Resource, Location, Domain, User, Group, Template]

  locations:

    # --- TU CATALOGO ---
    - type: file
      target: ../../catalog/domains/*.yaml

    - type: file
      target: ../../catalog/systems/*.yaml

    - type: file
      target: ../../catalog/tools/*.yaml

    - type: file
      target: ../../catalog/libraries/*.yaml

    - type: file
      target: ../../catalog/services/*.yaml

    # --- EJEMPLOS BACKSTAGE ---
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes: {}

permission:
  enabled: true